-- Select the database to use for the following operations
USE COVID_portfolio;

-- Create a new table called 'deaths' to store COVID-related death statistics
CREATE TABLE deaths (
    iso_code VARCHAR(255) NULL,
    continent VARCHAR(255) NULL,
    location VARCHAR(255) NULL,
    date DATE NULL,
    population BIGINT NULL DEFAULT NULL,
    total_cases INT NULL DEFAULT NULL,
    new_cases INT NULL DEFAULT NULL,
    new_cases_smoothed DECIMAL(13, 3) NULL DEFAULT NULL,
    total_deaths INT NULL DEFAULT NULL,
    new_deaths INT NULL DEFAULT NULL,
    new_deaths_smoothed DECIMAL(13, 3) NULL DEFAULT NULL,
    total_cases_per_million DECIMAL(13, 3) NULL DEFAULT NULL,
    new_cases_per_million DECIMAL(13, 3) NULL DEFAULT NULL,
    new_cases_smoothed_per_million DECIMAL(13, 3) NULL DEFAULT NULL,
    total_deaths_per_million DECIMAL(13, 3) NULL DEFAULT NULL,
    new_deaths_per_million DECIMAL(13, 3) NULL DEFAULT NULL,
    new_deaths_smoothed_per_million DECIMAL(13, 3) NULL DEFAULT NULL,
    reproduction_rate DECIMAL(13, 3) NULL DEFAULT NULL,
    icu_patients INT NULL DEFAULT NULL,
    icu_patients_per_million DECIMAL(13, 3) NULL DEFAULT NULL,
    hosp_patients INT NULL DEFAULT NULL,
    hosp_patients_per_million DECIMAL(13, 4) NULL DEFAULT NULL,
    weekly_icu_admissions INT NULL DEFAULT NULL,
    weekly_icu_admissions_per_million DECIMAL(13, 3) NULL DEFAULT NULL,
    weekly_hosp_admissions INT NULL DEFAULT NULL,
    weekly_hosp_admissions_per_million DECIMAL(13, 3) NULL DEFAULT NULL
);

-- Load the corresponding file
LOAD DATA INFILE '/Users/lucie/Documents/Work/Data_Sci/Portfolio/COVID/data/COVIDDeaths2.csv'
INTO TABLE deaths
FIELDS TERMINATED BY ';' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
  iso_code,
  continent,
  location,
  @date_var,
  @population,
  @total_cases,
  @new_cases,
  @new_cases_smoothed,
  @total_deaths,
  @new_deaths,
  @new_deaths_smoothed,
  @total_cases_per_million,
  @new_cases_per_million,
  @new_cases_smoothed_per_million,
  @total_deaths_per_million,
  @new_deaths_per_million,
  @new_deaths_smoothed_per_million,
  @reproduction_rate,
  @icu_patients,
  @icu_patients_per_million,
  @hosp_patients,
  @hosp_patients_per_million,
  @weekly_icu_admissions,
  @weekly_icu_admissions_per_million,
  @weekly_hosp_admissions,
  @weekly_hosp_admissions_per_million
)
SET 
  date = STR_TO_DATE(@date_var, '%d/%m/%Y'),
  population = NULLIF(TRIM(@population), ''),
  total_cases = NULLIF(TRIM(@total_cases), ''),
  new_cases = NULLIF(TRIM(@new_cases), ''),
  new_cases_smoothed = NULLIF(TRIM(@new_cases_smoothed), ''),
  total_deaths = NULLIF(TRIM(@total_deaths), ''),
  new_deaths = NULLIF(TRIM(@new_deaths), ''),
  new_deaths_smoothed = NULLIF(TRIM(@new_deaths_smoothed), ''),
  total_cases_per_million = NULLIF(TRIM(@total_cases_per_million), ''),
  new_cases_per_million = NULLIF(TRIM(@new_cases_per_million), ''),
  new_cases_smoothed_per_million = NULLIF(TRIM(@new_cases_smoothed_per_million), ''),
  total_deaths_per_million = NULLIF(TRIM(@total_deaths_per_million), ''),
  new_deaths_per_million = NULLIF(TRIM(@new_deaths_per_million), ''),
  new_deaths_smoothed_per_million = NULLIF(TRIM(@new_deaths_smoothed_per_million), ''),
  reproduction_rate = NULLIF(TRIM(@reproduction_rate), ''),
  icu_patients = NULLIF(TRIM(@icu_patients), ''),
  icu_patients_per_million = NULLIF(TRIM(@icu_patients_per_million), ''),
  hosp_patients = NULLIF(TRIM(@hosp_patients), ''),
  hosp_patients_per_million = NULLIF(TRIM(@hosp_patients_per_million), ''),
  weekly_icu_admissions = NULLIF(TRIM(@weekly_icu_admissions), ''),
  weekly_icu_admissions_per_million = NULLIF(TRIM(@weekly_icu_admissions_per_million), ''),
  weekly_hosp_admissions = NULLIF(TRIM(@weekly_hosp_admissions), ''),
  weekly_hosp_admissions_per_million = NULLIF(TRIM(@weekly_hosp_admissions_per_million), '');




-- Create a new table called 'vaccinations' to store COVID-vaccinations statistics
CREATE TABLE vaccinations (
iso_code VARCHAR(255) NULL,
continent VARCHAR(255) NULL,
location VARCHAR(255) NULL,
date DATE NULL,
new_tests INT NULL DEFAULT NULL,
total_tests INT NULL DEFAULT NULL,
total_tests_per_thousand DECIMAL(13, 3) NULL DEFAULT NULL,
new_tests_per_thousand DECIMAL(13, 3) NULL DEFAULT NULL,
new_tests_smoothed INT NULL DEFAULT NULL,
new_tests_smoothed_per_thousand DECIMAL(13, 3) NULL DEFAULT NULL,
positive_rate DECIMAL(13, 3) NULL DEFAULT NULL,
tests_per_case DECIMAL(13, 3) NULL DEFAULT NULL,
tests_units VARCHAR(255) NULL DEFAULT NULL,
total_vaccinations INT NULL DEFAULT NULL,
people_vaccinated INT NULL DEFAULT NULL,
people_fully_vaccinated INT NULL DEFAULT NULL,
new_vaccinations INT NULL DEFAULT NULL,
new_vaccinations_smoothed INT NULL DEFAULT NULL,
total_vaccinations_per_hundred DECIMAL(13, 3) NULL DEFAULT NULL,
people_vaccinated_per_hundred DECIMAL(13, 3) NULL DEFAULT NULL, 
people_fully_vaccinated_per_hundred DECIMAL(13, 3) NULL DEFAULT NULL,
new_vaccinations_smoothed_per_million DECIMAL(13, 3) NULL DEFAULT NULL,
stringency_index DECIMAL(13, 3) NULL DEFAULT NULL,
population_density DECIMAL(13, 3) NULL DEFAULT NULL,
median_age DECIMAL(13, 3) NULL DEFAULT NULL,
aged_65_older DECIMAL(13, 3) NULL DEFAULT NULL,
aged_70_older DECIMAL(13, 3) NULL DEFAULT NULL,
gdp_per_capita DECIMAL(13, 3) NULL DEFAULT NULL,
extreme_poverty DECIMAL(13, 3) NULL DEFAULT NULL,
cardiovasc_death_rate DECIMAL(13, 3) NULL DEFAULT NULL,
diabetes_prevalence DECIMAL(13, 3) NULL DEFAULT NULL,
female_smokers DECIMAL(13, 3) NULL DEFAULT NULL,
male_smokers DECIMAL(13, 3) NULL DEFAULT NULL,
handwashing_facilities DECIMAL(13, 3) NULL DEFAULT NULL,
hospital_beds_per_thousand DECIMAL(13, 3) NULL DEFAULT NULL,
life_expectancy DECIMAL(13, 3) NULL DEFAULT NULL,
human_development_index DECIMAL(13, 3) NULL DEFAULT NULL
);

-- Load the COVID vaccinations data from the specified CSV file into the 'vaccinations' table
LOAD DATA INFILE '/Users/lucie/Documents/Work/Data_Sci/Portfolio/COVID/data/COVIDVaccinations2.csv'
INTO TABLE vaccinations
FIELDS TERMINATED BY ';' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
  iso_code,
  continent,
  location,
  @date_var,
  @new_tests,
  @total_tests,
  @total_tests_per_thousand,
  @new_tests_per_thousand,
  @new_tests_smoothed,
  @new_tests_smoothed_per_thousand,
  @positive_rate,
  @tests_per_case,
  @tests_units,
  @total_vaccinations,
  @people_vaccinated,
  @people_fully_vaccinated,
  @new_vaccinations,
  @new_vaccinations_smoothed,
  @total_vaccinations_per_hundred,
  @people_vaccinated_per_hundred,
  @people_fully_vaccinated_per_hundred,
  @new_vaccinations_smoothed_per_million,
  @stringency_index,
  @population_density,
  @median_age,
  @aged_65_older,
  @aged_70_older,
  @gdp_per_capita,
  @extreme_poverty,
  @cardiovasc_death_rate,
  @diabetes_prevalence,
  @female_smokers,
  @male_smokers,
  @handwashing_facilities,
  @hospital_beds_per_thousand,
  @life_expectancy,
  @human_development_index
)
SET 
  date = STR_TO_DATE(@date_var, '%d/%m/%Y'),
  new_tests = NULLIF(TRIM(@new_tests), ''),
  total_tests = NULLIF(TRIM(@total_tests), ''),
  total_tests_per_thousand = NULLIF(TRIM(@total_tests_per_thousand), ''),
  new_tests_per_thousand = NULLIF(TRIM(@new_tests_per_thousand), ''),
  new_tests_smoothed = NULLIF(TRIM(@new_tests_smoothed), ''),
  new_tests_smoothed_per_thousand = NULLIF(TRIM(@new_tests_smoothed_per_thousand), ''),
  positive_rate = NULLIF(TRIM(@positive_rate), ''),
  tests_per_case = NULLIF(TRIM(@tests_per_case), ''),
  tests_units = NULLIF(TRIM(@tests_units), ''),
  total_vaccinations = NULLIF(TRIM(@total_vaccinations), ''),
  people_vaccinated = NULLIF(TRIM(@people_vaccinated), ''),
  people_fully_vaccinated = NULLIF(TRIM(@people_fully_vaccinated), ''),
  new_vaccinations = NULLIF(TRIM(@new_vaccinations), ''),
  new_vaccinations_smoothed = NULLIF(TRIM(@new_vaccinations_smoothed), ''),
  total_vaccinations_per_hundred = NULLIF(TRIM(@total_vaccinations_per_hundred), ''),
  people_vaccinated_per_hundred = NULLIF(TRIM(@people_vaccinated_per_hundred), ''),
  people_fully_vaccinated_per_hundred = NULLIF(TRIM(@people_fully_vaccinated_per_hundred), ''),
  new_vaccinations_smoothed_per_million = NULLIF(TRIM(@new_vaccinations_smoothed_per_million), ''),
  stringency_index = NULLIF(TRIM(@stringency_index), ''),
  population_density = NULLIF(TRIM(@population_density), ''),
  median_age = NULLIF(TRIM(@median_age), ''),
  aged_65_older = NULLIF(TRIM(@aged_65_older), ''),
  aged_70_older = NULLIF(TRIM(@aged_70_older), ''),
  gdp_per_capita = NULLIF(TRIM(@gdp_per_capita), ''),
  extreme_poverty = NULLIF(TRIM(@extreme_poverty), ''),
  cardiovasc_death_rate = NULLIF(TRIM(@cardiovasc_death_rate), ''),
  diabetes_prevalence = NULLIF(TRIM(@diabetes_prevalence), ''),
  female_smokers = NULLIF(TRIM(@female_smokers), ''),
  male_smokers = NULLIF(TRIM(@male_smokers), ''),
  handwashing_facilities = NULLIF(TRIM(@handwashing_facilities), ''),
  hospital_beds_per_thousand = NULLIF(TRIM(@hospital_beds_per_thousand), ''),
  life_expectancy = NULLIF(TRIM(@life_expectancy), ''),
  human_development_index = NULLIF(TRIM(@human_development_index), '');
